/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
          "on-secondary-container": "#785d23",
          "on-primary-fixed-variant": "#5d4200",
          "on-tertiary": "#ffffff",
          "secondary": "#755a21",
          "outline-variant": "#d4c4ac",
          "surface-container-low": "#fef9e6",
          "surface-container": "#f8f8f5",
          "secondary-container": "#fed892",
          "tertiary-container": "#dbeafe",
          "on-tertiary-fixed": "#001f2a",
          "surface-container-high": "#f3e6d6",
          "error-container": "#fee2e2",
          "on-secondary": "#ffffff",
          "on-error-container": "#991b1b",
          "surface-dim": "#f8f8f5",
          "on-surface-variant": "#504533",
          "on-tertiary-container": "#1e40af",
          "on-secondary-fixed": "#261900",
          "on-surface": "#1f1f1f",
          "surface-container-lowest": "#ffffff",
          "tertiary-fixed-dim": "#66d3ff",
          "surface": "#ffffff",
          "primary-fixed-dim": "#fdbb12",
          "inverse-surface": "#363025",
          "surface-tint": "#f5b400",
          "background": "#f8f8f5",
          "outline": "#827560",
          "inverse-primary": "#fdbb12",
          "primary-container": "#fff9e6",
          "error": "#f87171",
          "on-error": "#ffffff",
          "on-background": "#1f1f1f",
          "on-tertiary-fixed-variant": "#004d64",
          "on-primary": "#1f1f1f",
          "secondary-fixed-dim": "#e6c27e",
          "primary": "#f5b400",
          "on-primary-container": "#654900",
          "primary-fixed": "#ffdea4",
          "surface-variant": "#ede1d1",
          "inverse-on-surface": "#fbefde",
          "tertiary": "#60a5fa",
          "on-secondary-fixed-variant": "#5b430a",
          "surface-container-highest": "#ede1d1",
          "on-primary-fixed": "#261900",
          "tertiary-fixed": "#bde9ff",
          "secondary-fixed": "#ffdea4",
          "surface-bright": "#ffffff"
      },
      fontFamily: {
          "headline": ["Inter", "sans-serif"],
          "body": ["Inter", "sans-serif"],
          "label": ["Inter", "sans-serif"]
      },
      borderRadius: { "DEFAULT": "0.5rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
      boxShadow: {
          'card': '0 4px 20px -2px rgba(0, 0, 0, 0.05), 0 2px 8px -2px rgba(0, 0, 0, 0.03)',
      }
    },
  },
  plugins: [],
}
